"""Uses Claude to read a test failure and produce a Jira-ready bug report + priority."""
import json
from dataclasses import dataclass

from config import Config
from parse_results import TestFailure

VALID_PRIORITIES = ["Highest", "High", "Medium", "Low", "Lowest"]

SYSTEM_PROMPT = """You are a QA triage assistant. You are given a single automated test failure. Your job:
1. Write a clear, concise bug summary (one line, under 120 chars).
2. Write a bug description in Markdown with sections: Observed Behavior, Expected Behavior, Evidence, Suspected Area.
3. Assign a priority from exactly: Highest, High, Medium, Low, Lowest.
Respond with ONLY a JSON object: {"summary": "...", "description": "...", "priority": "...", "reasoning": "one sentence"}
"""


@dataclass
class TriageResult:
    summary: str
    description: str
    priority: str
    reasoning: str


def mock_triage_failure(failure: TestFailure) -> TriageResult:
    text = f"{failure.message} {failure.stack_trace}".lower()

    if any(w in text for w in ["crash", "nullpointer", "500", "segfault", "fatal"]):
        priority = "High"
        reasoning = "Mock rule: crash/server-error keywords found -> treated as High."
    elif any(w in text for w in ["timeout", "flaky", "intermittent"]):
        priority = "Lowest"
        reasoning = "Mock rule: timeout/flaky keywords found -> treated as Lowest."
    elif any(w in text for w in ["cosmetic", "typo", "spacing", "alignment"]):
        priority = "Low"
        reasoning = "Mock rule: cosmetic keywords found -> treated as Low."
    else:
        priority = "Medium"
        reasoning = "Mock rule: no strong signal found -> defaulted to Medium."

    summary = f"[MOCK] {failure.classname}::{failure.test_name} failed - {failure.message[:80]}"
    description = (
        f"## Observed Behavior\n{failure.message}\n\n"
        f"## Evidence\n{failure.stack_trace[:1000]}\n\n"
        f"## Suspected Area\n{failure.classname}\n\n"
        f"(This description was generated by the offline mock triage, not by Claude.)"
    )

    return TriageResult(summary=summary, description=description, priority=priority, reasoning=reasoning)


def triage_failure(failure: TestFailure) -> TriageResult:
    from anthropic import Anthropic
    client = Anthropic(api_key=Config.ANTHROPIC_API_KEY)

    user_content = (
        f"Test: {failure.classname}::{failure.test_name}\n"
        f"Suite: {failure.suite}\n"
        f"Kind: {failure.kind}\n"
        f"Duration: {failure.duration}s\n"
        f"Message: {failure.message}\n\n"
        f"Stack trace / details:\n{failure.stack_trace[:4000]}"
    )

    response = client.messages.create(
        model=Config.ANTHROPIC_MODEL,
        max_tokens=1000,
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": user_content}],
    )

    raw_text = "".join(
        block.text for block in response.content if getattr(block, "type", "") == "text"
    ).strip()

    if raw_text.startswith("```"):
        raw_text = raw_text.strip("`")
        if raw_text.lower().startswith("json"):
            raw_text = raw_text[4:].strip()

    try:
        data = json.loads(raw_text)
    except json.JSONDecodeError as e:
        raise ValueError(f"Could not parse triage JSON: {raw_text!r}") from e

    priority = data.get("priority", "Medium")
    if priority not in VALID_PRIORITIES:
        priority = "Medium"

    return TriageResult(
        summary=data.get("summary", f"{failure.classname}::{failure.test_name} failed"),
        description=data.get("description", failure.stack_trace[:2000]),
        priority=priority,
        reasoning=data.get("reasoning", ""),
    )
